---
- name: It's a basic yaml file
  hosts: 192.168.1.12
  tasks:
    - name: install apache
      yum:
        name: 
          - httpd
          - mod_ssl
          - mod_wsgii
        state: present
    - name: start and enable service of apache service  
      service:
        name: httpd
        state: started
        enabled: true
